#!/bin/bash
#
# Name the zip file and get md5
# Liquid

. $ANDROID_BUILD_TOP/vendor/liquid/tools/colors


OUT_TARGET_HOST=`uname -a | grep Darwin`
if [ -z "$OUT_TARGET_HOST" ]
then
   MD5=md5sum
else
   MD5="md5 -r "
fi

# Determine what to name the new signed package
if [ -z "$Liquid" ]; then
	MODVERSION=`sed -n -e'/ro\.liquid.version/s/^.*=//p' $OUT/system/build.prop`
	: ${MODVERSION:=}
        Device=`sed -n -e'/ro\.ota\.device/s/^.*=//p' $OUT/system/build.prop`
        : ${Device:=}
        OTA_TYPE=`sed -n -e'/ro\.ota\.type/s/^.*=//p' $OUT/system/build.prop`
        : ${OTA_TYPE:=}
        OTA_FILENAME=`sed -n -e'/ro\.ota\.version/s/^.*=//p' $OUT/system/build.prop`
        : ${OTA_FILENAME:=}
	LIQUID_TARGET_PACKAGE=$MODVERSION-$OTA_TYPE-$Device.zip
	OUTFILE=$OUT/$LIQUID_TARGET_PACKAGE
else
	LIQUID_TARGET_PACKAGE=liquid-squished.zip
	OUTFILE=$OUT/$LIQUID_TARGET_PACKAGE
fi

# Create a md5 checksum image of the repacked package
(
img=`basename $OUTFILE`
cd `dirname $OUTFILE`
ln -f *-ota-*.zip $LIQUID_TARGET_PACKAGE
rm *-ota-*.zip
$MD5 $img >$LIQUID_TARGET_PACKAGE.md5sum
ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
echo -e ${cya}"===========-Package complete-==========="${txtrst}
echo -e ${cya}"zip:"${cya}" $LIQUID_TARGET_PACKAGE"${txtrst}
echo -e ${cya}"md5:"${cya}" $(cat $LIQUID_TARGET_PACKAGE.md5sum | awk '{ print $1 }')"${txtrst}
echo -e ${cya}"size:"${cya}" $ZIPSIZE"${txtrst}
echo -e ${cya}"========================================"${txtrst}
)
